# Generated by Django 2.2 on 2019-12-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('dragon_id', models.AutoField(primary_key=True, serialize=False)),
                ('dragon_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_period', models.IntegerField()),
                ('max_animals_to_kill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DragonKillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_time', models.DateTimeField()),
                ('killed_animal', models.IntegerField()),
                ('dragon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragons_app.Dragon')),
            ],
        ),
    ]
