# Generated by Django 2.2 on 2019-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons_app', '0003_auto_20191213_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragonkillrecord',
            old_name='killed_animal',
            new_name='animals_to_kill',
        ),
        migrations.AlterField(
            model_name='dragonkillrecord',
            name='kill_time',
            field=models.CharField(max_length=255),
        ),
    ]
